version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo aws --version
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t hello-world:latest .
      - docker tag hello-world:latest 030637341606.dkr.ecr.ap-northeast-1.amazonaws.com/hello-world:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 030637341606.dkr.ecr.ap-northeast-1.amazonaws.com/hello-world:latest